"""vulture whitelist: names the framework reaches, not your code.

GENERATED by Proofmark gates/route_handlers.py. Regenerate after adding
routes, enum members, or framework subclasses; do not hand-edit. Every
name here is reached by something other than a call by name - decorator
registration for a route, value lookup for an enum member, by-name
dispatch from a stdlib framework onto a subclass override - so vulture
reports it as unwired code. Whitelisting is correct; grandfathering
these into the vulture baseline instead would make every new endpoint,
enum member, and framework override block its own commit.

Deliberately NOT here: ORM columns and settings fields. A column that
appears nowhere else is genuinely an unused column, and hiding that would
suppress the findings L003 exists to surface.
"""

# route handlers
_validation_error_handler  # src\api\app.py:115
agent_websocket  # src\api\routes\agent.py:85
analyze_url  # src\api\routes\analysis.py:23
ask  # src\api\routes\ask.py:58
cancel_scan  # src\api\routes\scans.py:252
chase_tip  # src\api\routes\leads.py:148
cost_projection  # src\api\routes\cost_projection.py:65
create_schedule  # src\api\routes\schedules.py:144
create_subscription  # src\api\routes\notifications.py:94
delete_schedule  # src\api\routes\schedules.py:187
delete_subscription  # src\api\routes\notifications.py:124
dismiss_tip  # src\api\routes\leads.py:137
estimate_cost  # src\api\routes\scans.py:280
get_api_key_status  # src\api\routes\settings.py:93
get_audit_logs  # src\api\routes\logs.py:69
get_cost_settings  # src\api\routes\settings.py:175
get_coverage  # src\api\routes\coverage.py:317
get_coverage_children  # src\api\routes\coverage.py:341
get_coverage_unresolved  # src\api\routes\coverage.py:367
get_domain  # src\api\routes\domains.py:51
get_keywords  # src\api\routes\keywords_admin.py:33
get_keywords_config  # src\api\routes\analysis.py:182
get_legiscan_usage  # src\api\routes\settings.py:162
get_log_info  # src\api\routes\logs.py:98
get_logs  # src\api\routes\logs.py:38
get_public_visibility  # src\api\routes\settings.py:211
get_scan  # src\api\routes\scans.py:175
get_settings  # src\api\routes\analysis.py:190
get_sheet_link  # src\api\routes\settings.py:140
get_sources_status  # src\api\routes\sources_admin.py:66
health  # src\api\app.py:271
library  # src\api\routes\policies.py:174
list_categories  # src\api\routes\domains.py:72
list_domains  # src\api\routes\domains.py:16
list_groups  # src\api\routes\domains.py:60
list_policies  # src\api\routes\policies.py:49
list_regions  # src\api\routes\domains.py:66
list_scans  # src\api\routes\scans.py:119
list_schedules  # src\api\routes\schedules.py:132
list_subscriptions  # src\api\routes\notifications.py:84
list_tags  # src\api\routes\domains.py:78
list_tips  # src\api\routes\leads.py:67
notifications_status  # src\api\routes\notifications.py:134
policy_stats  # src\api\routes\policies.py:262
reload_config_route  # src\api\routes\config_admin.py:14
remove_api_key  # src\api\routes\settings.py:228
root  # src\api\app.py:253
run_agent  # src\api\routes\agent.py:37
run_schedule_now  # src\api\routes\schedules.py:197
save_api_key  # src\api\routes\settings.py:112
scan_history  # src\api\routes\scans.py:144
scan_websocket  # src\api\routes\scans.py:264
search_places  # src\api\routes\search.py:19
search_plan  # src\api\routes\search.py:25
search_policies_text  # src\api\routes\policies.py:140
serve_frontend  # src\api\static_site.py:56
signals_status  # src\api\routes\signals.py:16
start_scan  # src\api\routes\scans.py:27
submit_tip  # src\api\routes\leads.py:80
update_cost_settings  # src\api\routes\settings.py:185
update_keyword_overrides  # src\api\routes\keywords_admin.py:99
update_public_visibility  # src\api\routes\settings.py:217
update_review_status  # src\api\routes\policies.py:217
update_schedule  # src\api\routes\schedules.py:166
update_source_enabled  # src\api\routes\sources_admin.py:89
update_subscription  # src\api\routes\notifications.py:108

# enum members
ACCESS_DENIED  # src\core\models.py:44
CANCELLED  # src\core\models.py:58
CAPTCHA_DETECTED  # src\core\models.py:42
COMPLETED  # src\core\models.py:56
COMPLETED  # src\core\models.py:64
DIRECTIVE  # src\core\models.py:27
DUPLICATE_URL  # src\core\models.py:73
FAILED  # src\core\models.py:57
FAILED  # src\core\models.py:65
FUTURE_DATE  # src\core\models.py:71
GENERIC_NAME  # src\core\models.py:72
GRANT  # src\core\models.py:30
GUIDANCE  # src\core\models.py:34
INCENTIVE  # src\core\models.py:28
JS_REQUIRED  # src\core\models.py:49
JURISDICTION_MISMATCH  # src\core\models.py:70
LAW  # src\core\models.py:25
LOGIN_REQUIRED  # src\core\models.py:43
LOW_CONFIDENCE_HIGH_SCORE  # src\core\models.py:74
MATCHING_PLATFORM  # src\core\models.py:35
NOT_FOUND  # src\core\models.py:45
PARSE_ERROR  # src\core\models.py:47
PAYWALL_DETECTED  # src\core\models.py:41
PENDING  # src\core\models.py:54
PENDING  # src\core\models.py:62
PLAN  # src\core\models.py:31
RATE_LIMITED  # src\core\models.py:48
REGULATION  # src\core\models.py:26
REQUIREMENT  # src\core\models.py:32
RUNNING  # src\core\models.py:55
RUNNING  # src\core\models.py:63
SKIPPED  # src\core\models.py:66
STANDARD  # src\core\models.py:33
SUCCESS  # src\core\models.py:40
TAX_INCENTIVE  # src\core\models.py:29
TIMEOUT  # src\core\models.py:46
UNKNOWN  # src\core\models.py:36
UNKNOWN_ERROR  # src\core\models.py:50
